CREATE DATABASE IF NOT EXISTS `SIB_BD`
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE `SIB_BD`;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `USU_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USU_LOGIN` VARCHAR(255) UNIQUE NOT NULL,
  `USU_SENHA` VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO `USUARIO` (`USU_ID`, `USU_LOGIN`, `USU_SENHA`) VALUES (NULL, 'ADM', 'ADM');

CREATE TABLE IF NOT EXISTS `PERFIL` (
  `PER_ID` INT NOT NULL AUTO_INCREMENT,
  `USU_ID` INT NOT NULL,
  `PER_NOME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PER_ID`, `USU_ID`),
  INDEX `FK_USUARIO_PERFIL` (`USU_ID`),
  CONSTRAINT `FK_USUARIO_PERFIL` FOREIGN KEY (`USU_ID`) REFERENCES `USUARIO` (`USU_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO `PERFIL` VALUES
(NULL, '1', 'Administrador'),
(NULL, '1', 'Empresa'),
(NULL, '1', 'Consultor');

CREATE TABLE IF NOT EXISTS `USUARIOS_CADASTRADOS` (
  `CAD_ID` INT NOT NULL AUTO_INCREMENT,
  `USU_ID` INT NOT NULL,
  `PER_ID` INT NOT NULL,
  `CAD_NOME` VARCHAR(255) NOT NULL,
  `CAD_EMAIL` VARCHAR(255) NOT NULL,
  `CAD_SENHA` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CAD_ID`, `USU_ID`),
  INDEX `FK_USUARIO_USUARIOS_CADASTRADOS` (`USU_ID`),
  INDEX `FK_PERFIL_USUARIOS_CADASTRADOS` (`PER_ID`),
  CONSTRAINT `FK_USUARIO_USUARIOS_CADASTRADOS` FOREIGN KEY (`USU_ID`) REFERENCES `USUARIO` (`USU_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_PERFIL_USUARIOS_CADASTRADOS` FOREIGN KEY (`PER_ID`) REFERENCES `PERFIL` (`PER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO `USUARIOS_CADASTRADOS` VALUES
(NULL, '1', '1', 'Marcos', 'marcos@gmail.com', ''),
(NULL, '1', '2', 'Fabio', 'fabio@sib.com', ''),
(NULL, '1', '3', 'Vinicius', 'vinicius@gmail.com', '');
