CREATE DATABASE IF NOT EXISTS `SIB_BD`
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE `SIB_BD`;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `USU_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USU_LOGIN` VARCHAR(255) UNIQUE NOT NULL,
  `USU_SENHA` VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO `USUARIO` (`USU_ID`, `USU_LOGIN`, `USU_SENHA`) VALUES (NULL, 'ADM', 'ADM');
